force-app/main/default/objects/Fraud__c/Fraud__c.object-meta.xml
<CustomObject>
    <label>Fraud</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Fraud Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frauds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frauds</relationshipLabel>
    <relationshipName>Frauds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Fraud_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Amount__c</fullName>
    <label>Fraud Amount</label>
    <summarizedField>Fraud_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Fraud_Item__c.Fraud__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Fraud_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Reason__c</fullName>
    <label>Fraud Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fraud Reason 01</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 02</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 03</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 04</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 05</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 06</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 07</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 08</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Other_Reason_Detail__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason_Detail__c</fullName>
    <description>It is mandatory when fraud reason = other</description>
    <label>Other Reason Detail</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/Fraud_Attestation_Doc__c.object-meta.xml
<CustomObject>
    <label>Fraud Attestation Doc</label>
    <nameField>
        <label>Fraud Attestation Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraud Attestation Docs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <label>Document ID</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <label>Fraud</label>
    <referenceTo>Fraud__c</referenceTo>
    <relationshipLabel>Attestation Docs</relationshipLabel>
    <relationshipName>Attestation_Docs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Sign_Status__c.field-meta.xml
<CustomField>
    <fullName>Sign_Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Sign Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/Fraud_Item__c.object-meta.xml
<CustomObject>
    <label>Fraud Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fraud Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Item__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <label>Fraud</label>
    <referenceTo>Fraud__c</referenceTo>
    <relationshipLabel>Fraud Items</relationshipLabel>
    <relationshipName>Fraud_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Item Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Tx_Date__c.field-meta.xml
<CustomField>
    <fullName>Tx_Date__c</fullName>
    <label>Tx Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/lwc-gate/FraudController.cls
public with sharing class FraudController {
    // @AuraEnabled(cacheable = true)
    @AuraEnabled
    public static List<Fraud__c> getFraudsForFrontlineTeam(){
        try {
            List<Fraud__c> myFrauds = [
                SELECT Id, Name, Account__r.Id, Account__r.Name, 
                        Fraud_Amount__c, Fraud_Reason__c, Other_Reason_Detail__c, 
                        Status__c, Approval_Status__c, CreatedDate
                FROM Fraud__c
                WHERE CreatedById = :UserInfo.getUserId()
                ORDER BY Name DESC
            ];
            return myFrauds;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<User> getUserNames(List<String> userIds){
        try {
            return [select Id, Name, UserName from User where Id in :userIds];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static Fraud__c getFraudTrackingInfo(String fraudId){
        try {
            Fraud__c fraud = [
                SELECT Id, Name, Status__c, Approval_Status__c, CreatedById, CreatedDate, LastModifiedDate, LastModifiedById,
                    (SELECT OldValue, NewValue, CreatedById, CreatedDate
                     FROM Histories 
                     WHERE Field = 'Status__c' 
                     ORDER BY CreatedDate),
                    (SELECT Id, Name, Document_ID__c, Sign_Status__c, CreatedById, CreatedDate 
                     FROM Attestation_Docs__r)
                FROM Fraud__c
                WHERE Id = :fraudId
            ];
            return fraud;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Fraud__c getFraudById(String fraudId){
        try {
            Fraud__c fraud = [
                SELECT Id, Name, Account__r.Id, Account__r.Name, 
                        Fraud_Amount__c, Fraud_Reason__c, Other_Reason_Detail__c, 
                        Status__c, Approval_Status__c, CreatedDate, lastModifiedDate, 
                        (SELECT Id, Name, Item_Order__c, Tx_Date__c, Card_Number__c, Amount__c, Merchant__c 
                        FROM Fraud_Items__r)
                FROM Fraud__c
                WHERE id = :fraudId
            ];
            return fraud;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Fraud_Item__c> getFraudItemsByFraudId(String fraudId){
        try {
            List<Fraud_Item__c> ret = [
                SELECT Id, Name, Item_Order__c, Tx_Date__c, Card_Number__c, Amount__c, Merchant__c, Fraud__c
                FROM Fraud_Item__c
                WHERE Fraud__c = :fraudId
                Order By Item_Order__c
            ];
            return ret;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean syncFraudItems(String fraudId, List<Fraud_Item__c> newOrUpdated, List<String> deletedItemIds) {
        try {
            List<Fraud_Item__c> newItems = new List<Fraud_Item__c>();
            List<Fraud_Item__c> oldItems = new List<Fraud_Item__c>();
            for (Fraud_Item__c item: newOrUpdated) {
                if (item.Id == null) {
                    newItems.add(item);
                } else {
                    oldItems.add(item);
                }
            }
            // New
            if (newItems.size() > 0) {
                insert newItems;
            }
            // Update
            if (oldItems.size() > 0) {
                update oldItems;
            }
            // Delete
            if (deletedItemIds != null && deletedItemIds.size() > 0) {
                List<Fraud_Item__c> toBeDeleted = [ SELECT Id, Name FROM Fraud_Item__c WHERE Id in :deletedItemIds ];
                delete toBeDeleted;
            }
            return true;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}