force-app/main/default/objects/Fraud__c/Fraud__c.object-meta.xml
<CustomObject>
    <label>Fraud</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Fraud Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frauds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frauds</relationshipLabel>
    <relationshipName>Frauds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Fraud_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Amount__c</fullName>
    <label>Fraud Amount</label>
    <summarizedField>Fraud_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Fraud_Item__c.Fraud__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Fraud_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Reason__c</fullName>
    <label>Fraud Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fraud Reason 01</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 02</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 03</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 04</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 05</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 06</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 07</fullName>
            </value>
            <value>
                <fullName>Fraud Reason 08</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Other_Reason_Detail__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason_Detail__c</fullName>
    <description>It is mandatory when fraud reason = other</description>
    <label>Other Reason Detail</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/Fraud_Item__c.object-meta.xml
<CustomObject>
    <label>Fraud Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fraud Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Item__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <label>Fraud</label>
    <referenceTo>Fraud__c</referenceTo>
    <relationshipLabel>Fraud Items</relationshipLabel>
    <relationshipName>Fraud_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Item Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Item__c/fields/Tx_Date__c.field-meta.xml
<CustomField>
    <fullName>Tx_Date__c</fullName>
    <label>Tx Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/api-client/FraudApiClient.cls
public with sharing class FraudApiClient {
    private static final String BASE_URL = 'http://3.129.216.253:8080';
    private static final String GEN_ATTESTATION_PATH = '/api/v1/fraud-attestations';

    public FraudApiClient() {
    }

    public static Map<String, Object> genAttestationThenSendToSign(String fraudId) {
        Fraud__c fraud = [
            SELECT Id, Name, Account__r.Id, Account__r.Name, 
                    Fraud_Amount__c, Fraud_Reason__c, Other_Reason_Detail__c, 
                    Status__c, Approval_Status__c, CreatedDate, lastModifiedDate, 
                    (SELECT Id, Name, Item_Order__c, Tx_Date__c, Card_Number__c, Amount__c, Merchant__c 
                    FROM Fraud_Items__r)
            FROM Fraud__c
            WHERE id = :fraudId
        ];

        List<Map<String, Object>> items = new List<Map<String, Object>>();
        for (Fraud_Item__c item: fraud.Fraud_Items__r) {
            items.add(new Map<String, Object>{
                'txDate' => item.Tx_Date__c,
                'merchant' => item.Merchant__c,
                'cardNumber' => item.Card_Number__c,
                'amount' => item.Amount__c
            });
        }
        Map<String, Object> req = new Map<String, Object>{
            'signer' => new Map<String, Object>{
                'id' => UserInfo.getUserId(),
                'fullName' => 'David Junior',
                'email' => 'David.Smith@nowhere.com',
                'phone' => '416-886-9081'
            },
            'fraud' => new Map<String, Object> {
                'fraudNumber' => fraud.Name,
                'clientName' => fraud.Account__r.Name,
                'fraudReason' => fraud.Fraud_Reason__c,
                'otherReasonDetail' => Fraud.Other_Reason_Detail__c,
                'items' => items
            },
            'callback' => new Map<String, Object>{
                'callbackUrl' => 'https://your.sf.com/services/apexrest/your-service-path',
                'oauthUrl' => 'https://your.sf.com/services/oauth2/token',
                'grantType'=> 'client_credentials',
                'clientId' => 'your-client-id',
                'clientSecret' => 'your-client-secret'
            }
        };

        return callApi(GEN_ATTESTATION_PATH, 'POST', req);
    }

    private static Map<String, Object> callApi(String apiUri, String method, Map<String, Object> reqPayload) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(BASE_URL + apiUri); 
        req.setMethod(method);
        if (reqPayload != null) {
            req.setBody(JSON.serialize(reqPayload));
        }
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('x-oauth-client-id', 'george-zhou');
        req.setHeader('x-oauth-client-secret', 'N0Passw0rd888');
        System.debug('gz debug: >>> request: ' + req.getEndpoint() + ' ' + method);
        Http http = new Http();
        HttpResponse res = http.send(req);
        System.debug('gz debug: <<< response: ' + res.getStatusCode() + ' ' + res.getStatus());
        String resPayload = res.getBody();
        System.debug('gz debug: <<< response body: ' + resPayload);
        return (Map<String, Object>)JSON.deserializeUntyped(resPayload);
    }    
}