force-app/main/default/objects/Fraud__c/Fraud__c.object-meta.xml
<CustomObject>
    <label>Fraud</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Fraud Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frauds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Attestation_Doc__c/Fraud_Attestation_Doc__c.object-meta.xml
<CustomObject>
    <label>Fraud Attestation Doc</label>
    <nameField>
        <label>Fraud Attestation Doc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraud Attestation Docs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <label>Document ID</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <label>Fraud</label>
    <referenceTo>Fraud__c</referenceTo>
    <relationshipLabel>Attestation Docs</relationshipLabel>
    <relationshipName>Attestation_Docs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Sign_Status__c.field-meta.xml
<CustomField>
    <fullName>Sign_Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Sign Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fraud_Attestation_Doc__c/fields/Signed_Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Signed_Document_ID__c</fullName>
    <description>Signed Version Document ID</description>
    <label>Signed Document ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/lwc-gate/FraudApexService.cls
@RestResource(urlMapping='/fraud/v1/esign/status/callback/*')
global with sharing class FraudApexService {
    public FraudApexService() {

    }

    @HttpPost
    global static void esignStatusCallback() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String uri = req.requestURI;
        String callbackEventName = uri.substring(uri.lastIndexOf('/') + 1);
        String jsonStr = req.requestBody.toString();
        Map<String, Object> jsonObj = (Map<String, Object>) JSON.deserializeUntyped(jsonStr);
        String docId = (String) jsonObj.get('documentId');
        String signedDocId = (String) jsonObj.get('signedDocumentId');
        String signedBase64PDF = (String) jsonObj.get('signedBase64Content');

        Fraud_Attestation_Doc__c docRec = [
            SELECT Id, Sign_Status__c, Signed_Document_ID__c, Fraud__c
            FROM Fraud_Attestation_Doc__c
            WHERE Name = :docId
        ];
        // WHERE Document_ID__C = :docId     // is ok too, but since Name is naturally ordered and it saves docId already for now
        docRec.Sign_Status__c = 'Completed';
        docRec.Signed_Document_ID__c = signedDocId;
        update docRec;

        String signedContentDocId = insertDocAndReturnDocId(docRec.Fraud__c, signedDocId, signedBase64PDF);

        res.statusCode = 200;
        res.addHeader('Content-Type', 'application/json;charset=UTF-8');
        res.responseBody = Blob.valueOf('{"ok": true, "signStatus": "Completed"}');
    }

    private static String insertDocAndReturnDocId(String fraudId, String docId, String base64Data) {
        Blob decoded = EncodingUtil.base64Decode(base64Data);
        ContentVersion cv = new ContentVersion();
        cv.Title = docId;
        cv.PathOnClient = 'generated-' + docId + '.pdf';
        cv.VersionData = decoded;
        cv.IsMajorVersion = true;
        insert cv;

        //Get Content Document ID to link it 
        Id conDocId = [SELECT ContentDocumentId FROM 
                        ContentVersion WHERE Id =:cv.Id].ContentDocumentId;        
        
        // Create ContentDocumentLink
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = fraudId;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        insert cdl;

        return conDocId;
    }
}